<?php

namespace AppBundle\Repository;

use AppBundle\Entity\StockTransaction;

/**
 * StockTransactionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StockTransactionRepository extends \Doctrine\ORM\EntityRepository
{
    public function confirmStockTransaction(StockTransaction $stockTransaction){
        $stockTransaction->setConfirmationStatus(1);
        return $stockTransaction;
    }
}
