front_end:
    resource: "@FrontEndBundle/Resources/config/routing.yml"
    prefix:   /

api:
    resource: "@ApiBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation