services:
    meetup.api.user:
        class: ApiBundle\Services\UserService
        arguments: [ "@doctrine.orm.entity_manager", "@meetup.common" ]

    meetup.api.item:
        class: ApiBundle\Services\ItemService
        arguments: [ "@doctrine.orm.entity_manager", "@meetup.common" ]

    meetup.api.transaction:
        class: ApiBundle\Services\TransactionService
        arguments: [ "@doctrine.orm.entity_manager", "@meetup.common" ]

    meetup.builder.transaction:
        class: ApiBundle\Builder\TransactionBuilder

    meetup.common:
        class: AppBundle\Services\CommonService
        arguments: [ "@doctrine.orm.entity_manager" ]